USE [master]
GO

/****** Object:  Database [TangoManager]    Script Date: 09/02/2023 21:58:16 ******/
CREATE DATABASE [TangoManager]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TangoManager', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TangoManager.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TangoManager_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\TangoManager_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TangoManager] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TangoManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TangoManager] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TangoManager] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TangoManager] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TangoManager] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TangoManager] SET ARITHABORT OFF 
GO

ALTER DATABASE [TangoManager] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TangoManager] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TangoManager] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TangoManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TangoManager] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TangoManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TangoManager] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TangoManager] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TangoManager] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TangoManager] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TangoManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TangoManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TangoManager] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TangoManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TangoManager] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TangoManager] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TangoManager] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TangoManager] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TangoManager] SET  MULTI_USER 
GO

ALTER DATABASE [TangoManager] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TangoManager] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TangoManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TangoManager] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TangoManager] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TangoManager] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TangoManager] SET  READ_WRITE 
GO


